package enums;

public enum Action {
	REGISTERTOURNAMENT, MODIFYTOURNAMENT, DELETETOURNAMENT, MODIFYUSER,
	TOURNAMENTPROFILE, USERPROFILE, DELETEUSER, MODIFYUSERPAGE, ADDTEAM, GENERATEFIXTURE,
	FIXTUREPAGE, ADDDATE, RESULTSERVLET, ADDRESULT, MODIFYRESULTSERVLET, MODIFYRESULT, ADDPLAYER, 
	TEAMPROFILEOVERLAY, DELETETEAM, DELETEPLAYER, MODIFYTEAMSERVLET, MODIFYTEAM, MODIFYTOURNAMENTPAGE,
	ADDGOALS, ADDGOALESSERVLET, OVERVIEW, CARDSERVLET, ADDYELLOWCARDS, ADDREDCARDS, ADDGREENCARDS, POSITIONPAGE, 
	RESULSTPAGE, CREATETOURNAMENTPAGE, ADDCOMMENT, SHOWCOMMENT, ADDUSER, TEAMPROFILE, MODIFYPLAYER, MODIFYPLAYERSERVLET

}
