package enums;

public enum Action {
	REGISTERTOURNAMENT, MODIFYTOURNAMENT, DELETETOURNAMENT, VERIFYADMINUSER, REGISTERUSER, MODIFYUSER, 
	TOURNAMENTPROFILE, TEAMSTOURNAMENT, USERPROFILE, DELETEUSER, MODIFYUSERPAGE, ADDTEAM, TEAMADDPAGE, GENERATEFIXTURE, 
	FIXTUREPAGE, ADDDATE, RESULTSERVLET, ADDRESULT, MODIFYRESULTSERVLET, MODIFYRESULT, ADDPLAYER, 
	TEAMPROFILEOVERLAY, DELETETEAM, DELETEPLAYER, MODIFYTEAMSERVLET, MODIFYTEAM, MODIFYTOURNAMENTPAGE,
	ADDGOALS, ADDGOALESSERVLET, OVERVIEW, CARDSERVLET, ADDYELLOWCARDS, ADDREDCARDS, ADDGREENCARDS, POSITIONPAGE, RESULSTPAGE, CREATETOURNAMENTPAGE, USERIMAGE, ADDCOMMENT, SHOWCOMMENT, ADDUSER 


}
